name: gogamedemo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  flutter_screenutil: ^1.1.0
  sqflite: ^1.3.1
  intl: ^0.16.1
  path_provider: ^1.6.10
  image_picker: ^0.6.6+5
  image_cropper: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

